export const DEFAULT_TAGS = [
  { slug: "1st_year", name: "1st Year" },
  { slug: "2nd_year", name: "2nd Year" },
  { slug: "3rd_year", name: "3rd Year" },
  { slug: "math", name: "Math" },
  { slug: "4th_year", name: "4th Year" },
  { slug: "lecture_focused", name: "Lecture Focused" },
  { slug: "cs", name: "CS" },
  { slug: "biology", name: "Biology" },
  { slug: "chemistry", name: "Chemistry" },
  { slug: "all_welcomed", name: "All Welcomed" },
  { slug: "enrolled_only", name: "Enrolled Only" },
  { slug: "physics", name: "Physics" },
  { slug: "algorithms", name: "Algorithms" },
  { slug: "exam_prep", name: "Exam Prep" },
];
